apiVersion: v1
kind: Service
metadata:
  name: web-game
  labels:
    app: web-game
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: web-game